//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace luyendoanhnghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBan
    {
        public int MaHD_ { get; set; }
        public Nullable<int> MaSach { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
